import { readdirSync, readFileSync, writeFileSync } from "fs";

// Builds src/<VideoName>/data.ts directly from the real ElevenLabs
// with-timestamps JSON files (public/voiceover/<VideoName>/beat-*.json) —
// never hand-transcribed, so on-screen text and timing can never drift from
// the actual audio. Run after generate-voiceover-<name>.ts, and again any
// time that script is re-run (new voice, regenerated pauses, etc.):
//
//   node --experimental-strip-types scripts/build-timing-data.ts <VideoName>

const videoName = process.argv[2];
if (!videoName) {
  throw new Error("Usage: build-timing-data.ts <VideoName>");
}

const voiceoverDir = `public/voiceover/${videoName}`;
const outPath = `src/${videoName}/data.ts`;

const files = readdirSync(voiceoverDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

if (files.length === 0) {
  throw new Error(`No beat-*.json files found in ${voiceoverDir}`);
}

let out = `export type WordTiming = { text: string; startMs: number; endMs: number };

export type Beat = {
  id: string;
  durationMs: number;
  words: WordTiming[];
};

// Word-level timings come straight from the ElevenLabs \`with-timestamps\`
// response for each beat (see public/voiceover/${videoName}/beat-XX.json,
// generated by scripts/generate-voiceover-*.ts via scripts/lib/elevenlabs.ts).
// This file is generated directly from that JSON by
// scripts/build-timing-data.ts — never hand-transcribed, so it cannot drift
// from the real audio.

export const BEATS: Record<string, Beat> = {
`;

for (const file of files) {
  const id = file.replace(".json", "");
  const data = JSON.parse(readFileSync(`${voiceoverDir}/${file}`, "utf8"));
  out += `  "${id}": {\n    id: "${id}",\n    durationMs: ${Math.round(data.durationMs)},\n    words: [\n`;
  for (const w of data.words) {
    const text = w.text.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    out += `      { text: "${text}", startMs: ${Math.round(w.startMs)}, endMs: ${Math.round(w.endMs)} },\n`;
  }
  out += `    ],\n  },\n`;
}

out += `};\n`;

writeFileSync(outPath, out);
console.log(`Wrote ${outPath}, ${out.split("\n").length} lines (${files.length} beats)`);
